BEGIN;

ALTER TABLE gastos_fijos
  ADD COLUMN IF NOT EXISTS activo_desde_ciclo VARCHAR(7) NOT NULL DEFAULT TO_CHAR(CURRENT_DATE, 'YYYY-MM'),
  ADD COLUMN IF NOT EXISTS activo_hasta_ciclo VARCHAR(7);

COMMIT;
